services:
  - type: web
    name: car-management-api
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/vehicles/health
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx256m
